#!/bin/sh

DEBUG=

generating_process() {
	# Generate thumbnails via Fast Skim process
	ezthumb $DEBUG -p skim -x _skim $IFILE
	ezthumb $DEBUG -p skim -x _skim_ha --accurate $IFILE

	# Generate thumbnails via Scan process
	ezthumb $DEBUG -p scan -x _scan $IFILE
	ezthumb $DEBUG -p scan -x _scan_ha_dotf --accurate --decode-otf $IFILE

	# Generate thumbnails via Two-pass Scan process
	ezthumb $DEBUG -p twopass -x _2pass $IFILE
	ezthumb $DEBUG -p twopass -x _2pass_ha --accurate $IFILE
	ezthumb $DEBUG -p twopass -x _2pass_ha_dotf --accurate --decode-otf $IFILE

	# Generate thumbnails via Heuristic process
	ezthumb $DEBUG -p heuris -x _heur $IFILE
	ezthumb $DEBUG -p heuris -x _heur_ha --accurate $IFILE
	ezthumb $DEBUG -p heuris -x _heur_ha_dotf --accurate --decode-otf $IFILE
}

if [ "$1" = "" ]; then
	echo no iuput file found
	exit 0
fi

for IFILE in $*
do
	generating_process
done

