
/*
    Copyright (C) 2011  "Andy Xuming" <xuming@users.sourceforge.net>

    This file is part of EZTHUMB, a utility to generate thumbnails

    EZTHUMB is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    EZTHUMB is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "id_lookup.h"

struct	idtbl	id_codec_flag[] = {
	{ CODEC_FLAG_QSCALE, "CODEC_FLAG_QSCALE" },
	{ CODEC_FLAG_4MV, "CODEC_FLAG_4MV" },
	{ CODEC_FLAG_QPEL, "CODEC_FLAG_QPEL" },
	{ CODEC_FLAG_GMC, "CODEC_FLAG_GMC" },
	{ CODEC_FLAG_MV0, "CODEC_FLAG_MV0" },
	{ CODEC_FLAG_PART, "CODEC_FLAG_PART" },
	{ CODEC_FLAG_INPUT_PRESERVED, "CODEC_FLAG_INPUT_PRESERVED" },
	{ CODEC_FLAG_PASS1, "CODEC_FLAG_PASS1" },
	{ CODEC_FLAG_PASS2, "CODEC_FLAG_PASS2" },
	{ CODEC_FLAG_EXTERN_HUFF, "CODEC_FLAG_EXTERN_HUFF" },
	{ CODEC_FLAG_GRAY, "CODEC_FLAG_GRAY" },
	{ CODEC_FLAG_EMU_EDGE, "CODEC_FLAG_EMU_EDGE" },
	{ CODEC_FLAG_PSNR, "CODEC_FLAG_PSNR" },
	{ CODEC_FLAG_TRUNCATED, "CODEC_FLAG_TRUNCATED" },
	{ CODEC_FLAG_NORMALIZE_AQP, "CODEC_FLAG_NORMALIZE_AQP" },
	{ CODEC_FLAG_INTERLACED_DCT, "CODEC_FLAG_INTERLACED_DCT" },
	{ CODEC_FLAG_LOW_DELAY, "CODEC_FLAG_LOW_DELAY" },
	{ CODEC_FLAG_ALT_SCAN, "CODEC_FLAG_ALT_SCAN" },
	{ CODEC_FLAG_GLOBAL_HEADER, "CODEC_FLAG_GLOBAL_HEADER" },
	{ CODEC_FLAG_BITEXACT, "CODEC_FLAG_BITEXACT" },
	{ CODEC_FLAG_AC_PRED, "CODEC_FLAG_AC_PRED" },
	{ CODEC_FLAG_H263P_UMV, "CODEC_FLAG_H263P_UMV" },
	{ CODEC_FLAG_CBP_RD, "CODEC_FLAG_CBP_RD" },
	{ CODEC_FLAG_QP_RD, "CODEC_FLAG_QP_RD" },
	{ CODEC_FLAG_H263P_AIV, "CODEC_FLAG_H263P_AIV" },
	{ CODEC_FLAG_OBMC, "CODEC_FLAG_OBMC" },
	{ CODEC_FLAG_LOOP_FILTER, "CODEC_FLAG_LOOP_FILTER" },
	{ CODEC_FLAG_H263P_SLICE_STRUCT, "CODEC_FLAG_H263P_SLICE_STRUCT" },
	{ CODEC_FLAG_INTERLACED_ME, "CODEC_FLAG_INTERLACED_ME" },
	{ CODEC_FLAG_SVCD_SCAN_OFFSET, "CODEC_FLAG_SVCD_SCAN_OFFSET" },
	{ CODEC_FLAG_CLOSED_GOP, "CODEC_FLAG_CLOSED_GOP" },
	{ CODEC_FLAG2_FAST, "CODEC_FLAG2_FAST" },
	{ CODEC_FLAG2_STRICT_GOP, "CODEC_FLAG2_STRICT_GOP" },
	{ CODEC_FLAG2_NO_OUTPUT, "CODEC_FLAG2_NO_OUTPUT" },
	{ CODEC_FLAG2_LOCAL_HEADER, "CODEC_FLAG2_LOCAL_HEADER" },
	{ CODEC_FLAG2_BPYRAMID, "CODEC_FLAG2_BPYRAMID" },
	{ CODEC_FLAG2_WPRED, "CODEC_FLAG2_WPRED" },
	{ CODEC_FLAG2_MIXED_REFS, "CODEC_FLAG2_MIXED_REFS" },
	{ CODEC_FLAG2_8X8DCT, "CODEC_FLAG2_8X8DCT" },
	{ CODEC_FLAG2_FASTPSKIP, "CODEC_FLAG2_FASTPSKIP" },
	{ CODEC_FLAG2_AUD, "CODEC_FLAG2_AUD" },
	{ CODEC_FLAG2_BRDO, "CODEC_FLAG2_BRDO" },
	{ CODEC_FLAG2_INTRA_VLC, "CODEC_FLAG2_INTRA_VLC" },
	{ CODEC_FLAG2_MEMC_ONLY, "CODEC_FLAG2_MEMC_ONLY" },
	{ CODEC_FLAG2_DROP_FRAME_TIMECODE, "CODEC_FLAG2_DROP_FRAME_TIMECODE" },
	{ CODEC_FLAG2_SKIP_RD, "CODEC_FLAG2_SKIP_RD" },
	{ CODEC_FLAG2_CHUNKS, "CODEC_FLAG2_CHUNKS" },
	{ CODEC_FLAG2_NON_LINEAR_QUANT, "CODEC_FLAG2_NON_LINEAR_QUANT" },
	{ CODEC_FLAG2_BIT_RESERVOIR, "CODEC_FLAG2_BIT_RESERVOIR" },
	{ CODEC_FLAG2_MBTREE, "CODEC_FLAG2_MBTREE" },
	{ CODEC_FLAG2_PSY, "CODEC_FLAG2_PSY" },
	{ CODEC_FLAG2_SSIM, "CODEC_FLAG2_SSIM" },
	{ 0, NULL }
};


