
/*
    Copyright (C) 2011  "Andy Xuming" <xuming@users.sourceforge.net>

    This file is part of EZTHUMB, a utility to generate thumbnails

    EZTHUMB is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    EZTHUMB is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "id_lookup.h"

struct	idtbl	id_pix_fmt[] = {
	{ PIX_FMT_NONE, "PIX_FMT_NONE" },
	{ PIX_FMT_YUV420P, "PIX_FMT_YUV420P" },
	{ PIX_FMT_YUYV422, "PIX_FMT_YUYV422" },
	{ PIX_FMT_RGB24, "PIX_FMT_RGB24" },
	{ PIX_FMT_BGR24, "PIX_FMT_BGR24" },
	{ PIX_FMT_YUV422P, "PIX_FMT_YUV422P" },
	{ PIX_FMT_YUV444P, "PIX_FMT_YUV444P" },
	{ PIX_FMT_YUV410P, "PIX_FMT_YUV410P" },
	{ PIX_FMT_YUV411P, "PIX_FMT_YUV411P" },
	{ PIX_FMT_GRAY8, "PIX_FMT_GRAY8" },
	{ PIX_FMT_MONOWHITE, "PIX_FMT_MONOWHITE" },
	{ PIX_FMT_MONOBLACK, "PIX_FMT_MONOBLACK" },
	{ PIX_FMT_PAL8, "PIX_FMT_PAL8" },
	{ PIX_FMT_YUVJ420P, "PIX_FMT_YUVJ420P" },
	{ PIX_FMT_YUVJ422P, "PIX_FMT_YUVJ422P" },
	{ PIX_FMT_YUVJ444P, "PIX_FMT_YUVJ444P" },
	{ PIX_FMT_XVMC_MPEG2_MC, "PIX_FMT_XVMC_MPEG2_MC" },
	{ PIX_FMT_XVMC_MPEG2_IDCT, "PIX_FMT_XVMC_MPEG2_IDCT" },
	{ PIX_FMT_UYVY422, "PIX_FMT_UYVY422" },
	{ PIX_FMT_UYYVYY411, "PIX_FMT_UYYVYY411" },
	{ PIX_FMT_BGR8, "PIX_FMT_BGR8" },
	{ PIX_FMT_BGR4, "PIX_FMT_BGR4" },
	{ PIX_FMT_BGR4_BYTE, "PIX_FMT_BGR4_BYTE" },
	{ PIX_FMT_RGB8, "PIX_FMT_RGB8" },
	{ PIX_FMT_RGB4, "PIX_FMT_RGB4" },
	{ PIX_FMT_RGB4_BYTE, "PIX_FMT_RGB4_BYTE" },
	{ PIX_FMT_NV12, "PIX_FMT_NV12" },
	{ PIX_FMT_NV21, "PIX_FMT_NV21" },
	{ PIX_FMT_ARGB, "PIX_FMT_ARGB" },
	{ PIX_FMT_RGBA, "PIX_FMT_RGBA" },
	{ PIX_FMT_ABGR, "PIX_FMT_ABGR" },
	{ PIX_FMT_BGRA, "PIX_FMT_BGRA" },
	{ PIX_FMT_GRAY16BE, "PIX_FMT_GRAY16BE" },
	{ PIX_FMT_GRAY16LE, "PIX_FMT_GRAY16LE" },
	{ PIX_FMT_YUV440P, "PIX_FMT_YUV440P" },
	{ PIX_FMT_YUVJ440P, "PIX_FMT_YUVJ440P" },
	{ PIX_FMT_YUVA420P, "PIX_FMT_YUVA420P" },
	{ PIX_FMT_VDPAU_H264, "PIX_FMT_VDPAU_H264" },
	{ PIX_FMT_VDPAU_MPEG1, "PIX_FMT_VDPAU_MPEG1" },
	{ PIX_FMT_VDPAU_MPEG2, "PIX_FMT_VDPAU_MPEG2" },
	{ PIX_FMT_VDPAU_WMV3, "PIX_FMT_VDPAU_WMV3" },
	{ PIX_FMT_VDPAU_VC1, "PIX_FMT_VDPAU_VC1" },
	{ PIX_FMT_RGB48BE, "PIX_FMT_RGB48BE" },
	{ PIX_FMT_RGB48LE, "PIX_FMT_RGB48LE" },
	{ PIX_FMT_RGB565BE, "PIX_FMT_RGB565BE" },
	{ PIX_FMT_RGB565LE, "PIX_FMT_RGB565LE" },
	{ PIX_FMT_RGB555BE, "PIX_FMT_RGB555BE" },
	{ PIX_FMT_RGB555LE, "PIX_FMT_RGB555LE" },
	{ PIX_FMT_BGR565BE, "PIX_FMT_BGR565BE" },
	{ PIX_FMT_BGR565LE, "PIX_FMT_BGR565LE" },
	{ PIX_FMT_BGR555BE, "PIX_FMT_BGR555BE" },
	{ PIX_FMT_BGR555LE, "PIX_FMT_BGR555LE" },
	{ PIX_FMT_VAAPI_MOCO, "PIX_FMT_VAAPI_MOCO" },
	{ PIX_FMT_VAAPI_IDCT, "PIX_FMT_VAAPI_IDCT" },
	{ PIX_FMT_VAAPI_VLD, "PIX_FMT_VAAPI_VLD" },
	{ PIX_FMT_YUV420P16LE, "PIX_FMT_YUV420P16LE" },
	{ PIX_FMT_YUV420P16BE, "PIX_FMT_YUV420P16BE" },
	{ PIX_FMT_YUV422P16LE, "PIX_FMT_YUV422P16LE" },
	{ PIX_FMT_YUV422P16BE, "PIX_FMT_YUV422P16BE" },
	{ PIX_FMT_YUV444P16LE, "PIX_FMT_YUV444P16LE" },
	{ PIX_FMT_YUV444P16BE, "PIX_FMT_YUV444P16BE" },
	{ PIX_FMT_VDPAU_MPEG4, "PIX_FMT_VDPAU_MPEG4" },
	{ PIX_FMT_DXVA2_VLD, "PIX_FMT_DXVA2_VLD" },
	{ PIX_FMT_RGB444BE, "PIX_FMT_RGB444BE" },
	{ PIX_FMT_RGB444LE, "PIX_FMT_RGB444LE" },
	{ PIX_FMT_BGR444BE, "PIX_FMT_BGR444BE" },
	{ PIX_FMT_BGR444LE, "PIX_FMT_BGR444LE" },
	{ PIX_FMT_Y400A, "PIX_FMT_Y400A" },
	{ PIX_FMT_NB, "PIX_FMT_NB" },
	{ 0, NULL },
};

