#!/bin/bash

FINDARG="-H -n"
USAGE="Usage:  xfind [-w][-i] FILETYPE STRING\n\
for example: xfind '*.c' 'hello world'"


while [ $# != 0 ]
do  case "$1" in
  -w) FINDARG="$FINDARG -w" ;;
  -i) FINDARG="$FINDARG -i" ;;
  -h|--help|-*)  echo -e $USAGE; exit 0 ;;
  *) break ;;
  esac
  shift
done

#echo [$FINDARG] [$*] [$#]

if test $# -lt 2 ; then
	echo -e $USAGE
	exit 0
fi

find . -name "$1" -exec grep $FINDARG "$2" {} \;

